# Generated by Django 2.2.3 on 2019-09-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asambleista',
            fields=[
                ('id_asambleista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('partido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ley',
            fields=[
                ('id_ley', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_oficial', models.CharField(max_length=300)),
                ('nombre_publico', models.CharField(max_length=300)),
                ('fecha', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('ruta_imagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=10)),
                ('usuario_nombre', models.CharField(max_length=20)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=35)),
                ('fecha', models.CharField(max_length=35)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(max_length=35)),
                ('id_asambleista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.Asambleista')),
                ('id_ley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.Ley')),
            ],
            options={
                'unique_together': {('id_ley', 'id_asambleista')},
            },
        ),
        migrations.CreateModel(
            name='ComentarioLey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.Comentario')),
                ('id_ley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.Ley')),
            ],
            options={
                'unique_together': {('id_ley', 'id_comentario')},
            },
        ),
    ]
